export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  JURY: 'JURY',
  CREATOR: 'CREATOR',
  PUBLIC_USER: 'PUBLIC_USER'
};

export const ROLE_HIERARCHY = {
  SUPER_ADMIN: 100,
  ADMIN: 80,
  MODERATOR: 60,
  JURY: 40,
  CREATOR: 20,
  PUBLIC_USER: 10
};
